In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../data/processed/cleaned_metal_prices.csv")
df.head()

,Date,Year,Month,Price_alum,Price_gold,Price_nickel,Price_silver,Price_uran,Inflation_rate,Price_alum_infl,Price_gold_infl,Price_nickel_infl,Price_silver_infl,Price_uran_infl
0,1992-02-01,1992,Feb,1266.83,353.91,7861.9,4.15,7.90,89.59,2401.782997,670.977969,14905.37621,7.867985,14.977610
1,1992-03-01,1992,Mar,1280.47,344.34,7417.7,4.11,7.75,89.59,2427.643073,652.834206,14063.21743,7.792149,14.693225
2,1992-04-01,1992,Apr,1317.05,338.62,7420.6,4.05,7.75,89.59,2496.995095,641.989658,14068.71554,7.678395,14.693225
3,1992-05-01,1992,May,1306.79,337.24,7326.8,4.07,7.55,89.59,2477.543161,639.373316,13890.88012,7.716313,14.314045
4,1992-06-01,1992,Jun,1275.55,340.81,7192.8,4.06,7.75,89.59,2418.315245,646.141679,13636.82952,7.697354,14.693225

In [6]:
df.isnull().sum()

Date                 0
Year                 0
Month                0
Price_alum           0
Price_gold           0
Price_nickel         0
Price_silver         0
Price_uran           0
Inflation_rate       0
Price_alum_infl      0
Price_gold_infl      0
Price_nickel_infl    0
Price_silver_infl    0
Price_uran_infl      0
dtype: int64

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

In [8]:
df = df.sort_values("Date")
df.head()

,Date,Year,Month,Price_alum,Price_gold,Price_nickel,Price_silver,Price_uran,Inflation_rate,Price_alum_infl,Price_gold_infl,Price_nickel_infl,Price_silver_infl,Price_uran_infl
0,1992-02-01,1992,Feb,1266.83,353.91,7861.9,4.15,7.90,89.59,2401.782997,670.977969,14905.37621,7.867985,14.977610
1,1992-03-01,1992,Mar,1280.47,344.34,7417.7,4.11,7.75,89.59,2427.643073,652.834206,14063.21743,7.792149,14.693225
2,1992-04-01,1992,Apr,1317.05,338.62,7420.6,4.05,7.75,89.59,2496.995095,641.989658,14068.71554,7.678395,14.693225
3,1992-05-01,1992,May,1306.79,337.24,7326.8,4.07,7.55,89.59,2477.543161,639.373316,13890.88012,7.716313,14.314045
4,1992-06-01,1992,Jun,1275.55,340.81,7192.8,4.06,7.75,89.59,2418.315245,646.141679,13636.82952,7.697354,14.693225

In [9]:
df["Year"] = df["Date"].dt.year
df["Month_Num"] = df["Date"].dt.month
df["Quarter"] = df["Date"].dt.quarter
df.head()

,Date,Year,Month,Price_alum,Price_gold,Price_nickel,Price_silver,Price_uran,Inflation_rate,Price_alum_infl,Price_gold_infl,Price_nickel_infl,Price_silver_infl,Price_uran_infl,Month_Num,Quarter
0,1992-02-01,1992,Feb,1266.83,353.91,7861.9,4.15,7.90,89.59,2401.782997,670.977969,14905.37621,7.867985,14.977610,2,1
1,1992-03-01,1992,Mar,1280.47,344.34,7417.7,4.11,7.75,89.59,2427.643073,652.834206,14063.21743,7.792149,14.693225,3,1
2,1992-04-01,1992,Apr,1317.05,338.62,7420.6,4.05,7.75,89.59,2496.995095,641.989658,14068.71554,7.678395,14.693225,4,2
3,1992-05-01,1992,May,1306.79,337.24,7326.8,4.07,7.55,89.59,2477.543161,639.373316,13890.88012,7.716313,14.314045,5,2
4,1992-06-01,1992,Jun,1275.55,340.81,7192.8,4.06,7.75,89.59,2418.315245,646.141679,13636.82952,7.697354,14.693225,6,2

For Gold, Silver, Aluminium, Nickel, Uranium

In [10]:
metals = ["Price_gold", "Price_silver", "Price_alum", "Price_nickel", "Price_uran" ]

Lag Features = previous values,

Rolling mean healps to smooth out any fluctuations or sudden spkies,

Volatality , percentage change

In [11]:
for metal in metals:

    #Lag Features
    df[f"{metal}_Lag_1"] = df[metal].shift(1)
    df[f"{metal}_Lag_2"] = df[metal].shift(2)
    df[f"{metal}_Lag_3"] = df[metal].shift(3)

    #Rolling Mean
    df[f"{metal}_Rolling_Mean_3"] = (df[metal].rolling(window=3).mean())

    #Percentage Returns
    df[f"{metal}_Returns"] = (df[metal].pct_change())

In [12]:
df.dropna(inplace=True)

In [13]:
df.head()

,Date,Year,Month,Price_alum,Price_gold,Price_nickel,Price_silver,Price_uran,Inflation_rate,Price_alum_infl,...,Price_nickel_Lag_1,Price_nickel_Lag_2,Price_nickel_Lag_3,Price_nickel_Rolling_Mean_3,Price_nickel_Returns,Price_uran_Lag_1,Price_uran_Lag_2,Price_uran_Lag_3,Price_uran_Rolling_Mean_3,Price_uran_Returns
3,1992-05-01,1992,May,1306.79,337.24,7326.8,4.07,7.55,89.59,2477.543161,...,7420.6,7417.7,7861.9,7388.366667,-0.012640,7.75,7.75,7.90,7.683333,-0.025806
4,1992-06-01,1992,Jun,1275.55,340.81,7192.8,4.06,7.75,89.59,2418.315245,...,7326.8,7420.6,7417.7,7313.400000,-0.018289,7.55,7.75,7.75,7.683333,0.026490
5,1992-07-01,1992,Jul,1313.05,352.72,7497.9,3.97,7.75,89.59,2489.411495,...,7192.8,7326.8,7420.6,7339.166667,0.042417,7.75,7.55,7.75,7.683333,0.000000
6,1992-08-01,1992,Aug,1305.05,343.06,7268.0,3.81,8.05,89.59,2474.244295,...,7497.9,7192.8,7326.8,7319.566667,-0.030662,7.75,7.75,7.55,7.850000,0.038710
7,1992-09-01,1992,Sep,1269.61,345.43,6917.5,3.77,8.75,89.59,2407.053599,...,7268.0,7497.9,7192.8,7227.800000,-0.048225,8.05,7.75,7.75,8.183333,0.086957

In [14]:
df.to_csv("../data/processed/feature_engineering_data.csv", index=False)

<!-- Gold -->

In [15]:
# df["Gold_Lag_1"] = df["Price_gold"].shift(1)
# df["Gold_Lag_2"] = df["Price_gold"].shift(2)
# df["Gold_Lag_3"] = df["Price_gold"].shift(3)

In [16]:
# df["Gold_Rolling_Mean_3"] = (df["Price_gold"].rolling(window = 3).mean())

In [17]:
# df["Gold_Returns"] = (df["Price_gold"].pct_change())

In [18]:
# df.dropna(inplace=True)

In [19]:
# df.head()

In [20]:
# df.to_csv("../data/processed/feature_engineering_data.csv", index=False)